pipeline {
     agent any
     stages {
        stage("Build") {
            steps {
                dir('GetYourWay/src/main/gywWebApp') {
                    sh "npm install"
                    sh "npm run build"
                }
            }
        }
        stage("Deploy") {
            steps {
                dir('GetYourWay/src/main/gywWebApp') {
                    sh 'serve -s build'
                }
            }
        }
    }
}