pipeline {
     agent any
     stages {
         stage("Install dependencies") {
        stage("Build") {
            steps {
                sh "sudo npm install"
                sh "sudo npm run build"
            }
        }
        stage("Deploy") {
            steps {
                sh 'sudo serve -s build'
            }
        }
    }
}